import React from "react";
import Head from "next/head";

const Layout = (props: { children: React.ReactChild }) => {
  return (
    <div className={"flex flex-col justify-center items-center h-full min-h-screen"}>
      <Head>
        <title>blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={""}>{props.children}</main>

      <footer className={""}>&copy; Ian Sinnott {new Date().getFullYear()}</footer>
    </div>
  );
};

export default Layout;
