import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className={"flex flex-col justify-center items-center h-full min-h-screen"}>
      <Head>
        <title>blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"bg-blue-300 mb-12 p-12 rounded-lg"}>
        <h1>In progress...</h1>
        <p>Currenlty moving my site away from Gatsby</p>
      </main>

      <footer className={""}>&copy; Ian Sinnott {new Date().getFullYear()}</footer>
    </div>
  );
};

export default Home;
